### ISSUE TITLE
Submodule not found https://github.com/kickstarter/native-secrets/

### ISSUE THREAD

**Issue by ngapq-misfit** [kickstarter/ios-oss#11]
Hi Kickstarter team,

I run "make bootstrap" and run into this issue. The "native-secrets" repo shows 404 "page not found". Could you please recheck? Thanks.

```
Cloning into 'Frameworks/ios-ksapi/Frameworks/native-secrets'...
remote: Repository not found.
fatal: repository 'https://github.com/kickstarter/native-secrets/' not found
```

**Comment by huangwei4478** [comment]
#7 it seems they are still working on it.

**Comment by wangxiaobupt** [comment]
the same problem with me.

**Comment by mbrandonw** [comment]
We hope we have fixed this with #13, can you try again?

**Comment by ngapq-misfit** [comment]
@mbrandonw I pull the latest code but still met the problem :(

```
Submodule path 'Frameworks/ios-ksapi/Frameworks/ReactiveExtensions/Frameworks/ReactiveCocoa/Carthage/Checkouts/xcconfigs': checked out '1ef97639ffbe041da0b1392b2114fa19b922a7a1'
rm -rf Frameworks/ios-ksapi/Frameworks/native-secrets
git clone https://github.com/kickstarter/native-secrets Frameworks/ios-ksapi/Frameworks/native-secrets
Cloning into 'Frameworks/ios-ksapi/Frameworks/native-secrets'...
remote: Repository not found.
fatal: repository 'https://github.com/kickstarter/native-secrets/' not found
make: [secrets] Error 128 (ignored)
```

**Comment by strogonoff** [comment]
@ngapq-misfit, after #13 you will still see the error output, but it’s now ignored and handled by putting example secrets in the directory at next step. Check out Frameworks/ios-ksapi/Frameworks/native-secrets for yourself, it should have contents.

It’s a bit clunky, esp. the error output, but it should work.

**Comment by ngapq-misfit** [comment]
@strogonoff Yay, I can build it now. Thanks ^^

**Comment by stephencelis** [comment]
Glad things are working now! We hope to clean up this process more soon.
